# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.CharField(max_length=50),
        ),
    ]
