# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.CharField(default='', max_length=50),
        ),
    ]
